name: guanjia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_easyloading: 3.0.5
  fluttertoast: 8.2.5
  get: 4.6.6
  cached_network_image: 3.3.1
  flutter_cache_manager: 3.3.2
  dio: 5.4.3+1 #网络请求
  photo_view: 0.15.0 #画廊
  flutter_staggered_grid_view: 0.7.0 #瀑布流
  flutter_pickers: 2.1.9 #城市选择
  flutter_slidable: 3.1.0 #滑动删除
  image_picker: 1.1.1 #相机拍照
  webview_flutter: 4.8.0 #webview
  permission_handler: 11.3.1 #权限管理
  common_utils: 2.1.0 #通用库
  image_gallery_saver: 2.0.3 #保存图片到图库
  shared_preferences: 2.2.3 #本地缓存
  package_info_plus: 8.0.0 #包管理
  system_clock: 2.0.0
  connectivity_plus: 6.0.3
  web_socket_channel: 3.0.0
  pretty_dio_logger: 1.3.1
  logger: 2.3.0
  dotted_border: 2.1.0
  soundpool: 2.4.1
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^4.0.0
  flutter_swiper_null_safety: ^1.0.2 #轮播

  scrollview_observer: ^1.20.0 # 滚动定位
  svgaplayer_flutter: ^2.2.0

  crypto: ^3.0.3 # 加密
  intl: 0.18.1
  auto_size_text: 3.0.0
  fading_edge_scrollview: ^4.1.1
  just_audio: ^0.9.38 # 音频播放
  path_provider: ^2.1.3
  path: 1.9.0
  collection: 1.18.0 # 集合扩展库
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+2
  device_info_plus: ^10.1.0
  in_app_purchase: ^3.2.0
  uuid: ^4.0.0
  intl_phone_field: ^3.2.0
  extended_image: ^8.2.1
  image_editor: ^1.5.1
  material_color_generator: ^1.1.0
  zego_zimkit: 1.18.10

dependency_overrides:
  http: ^1.2.1 # svgaplayer_flutter 和 flutter_cache_manager会冲突，强制使用flutter_cache_manager依赖版本
  webview_flutter_android: 3.16.1
  intl: 0.18.1
  win32: 5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/common/
    - assets/images/home/
    - assets/images/login/
    - assets/images/mine/
    - assets/images/discover/
    - assets/images/wallet/
    - assets/images/chat/
    - assets/images/order/
    - assets/js/
    #   - images/a_dot_ham.jpeg
flutter_intl:
  enabled: true
  main_locale: zh
